# yaml-language-server: $schema=https://json.schemastore.org/github-release-config.json

changelog:
    categories:
        - title: "Breaking Changes"
          labels:
              - "breaking change"
        - title: "Features"
          labels:
              - "enhancement"
        - title: "Fixes"
          labels:
              - "bug"
        - title: "Other Changes"
          labels:
              - "*"
