---
description: "Prettier plugin to force array elements to wrap onto new lines."
plugins:
    - "jekyll-sitemap"
    - "jekyll-seo-tag"
    - "jekyll-paginate"
    - "jekyll-feed"
    - "jekyll-archives"
    - "jekyll-language-plugin"
    - "jekyll-algolia"
    - "jekyll-mentions"
    - "jekyll-admin"
    - "jekyll-loading-lazy"
remote_theme: "pages-themes/hacker@v0.2.0"
title: "Prettier Plugin Multiline Arrays 2"
# The base hostname and protocol for your site.
url: "https://nick2bad4u.github.io/prettier-plugin-multiline-arrays-2"
