import nickTwoBadFourU from "eslint-config-nick2bad4u";

const legacySourceRuleOverrides = Object.fromEntries(
    [
        "@eslint-community/eslint-comments/require-description",
        "@typescript-eslint/consistent-indexed-object-style",
        "@typescript-eslint/consistent-type-definitions",
        "@typescript-eslint/explicit-module-boundary-types",
        "@typescript-eslint/no-explicit-any",
        "@typescript-eslint/no-import-type-side-effects",
        "@typescript-eslint/no-invalid-void-type",
        "@typescript-eslint/no-shadow",
        "@typescript-eslint/no-unsafe-argument",
        "@typescript-eslint/no-unsafe-assignment",
        "@typescript-eslint/no-unsafe-member-access",
        "@typescript-eslint/no-unsafe-return",
        "@typescript-eslint/no-unsafe-type-assertion",
        "@typescript-eslint/prefer-nullish-coalescing",
        "@typescript-eslint/prefer-readonly-parameter-types",
        "@typescript-eslint/prefer-reduce-type-parameter",
        "@typescript-eslint/prefer-regexp-exec",
        "@typescript-eslint/require-array-sort-compare",
        "@typescript-eslint/restrict-template-expressions",
        "@typescript-eslint/strict-boolean-expressions",
        "@virmator/prefer-params-object",
        "arrow-body-style",
        "canonical/filename-no-index",
        "canonical/no-re-export",
        "capitalized-comments",
        "complexity",
        "de-morgan/no-negated-conjunction",
        "etc-misc/no-param-reassign",
        "etc-misc/no-unnecessary-template-literal",
        "import-x/extensions",
        "import-x/no-anonymous-default-export",
        "import-x/no-extraneous-dependencies",
        "import-x/no-rename-default",
        "math/prefer-number-is-nan",
        "n/callback-return",
        "n/no-extraneous-import",
        "n/no-process-env",
        "n/no-process-exit",
        "n/no-unsupported-features/node-builtins",
        "nitpick/no-redundant-vars",
        "no-await-in-loop",
        "no-barrel-files/no-barrel-files",
        "no-console",
        "no-duplicate-imports",
        "no-else-return",
        "no-implicit-coercion",
        "no-param-reassign",
        "no-plusplus",
        "perfectionist/sort-arrays",
        "perfectionist/sort-imports",
        "perfectionist/sort-intersection-types",
        "perfectionist/sort-modules",
        "perfectionist/sort-named-imports",
        "perfectionist/sort-objects",
        "perfectionist/sort-object-types",
        "perfectionist/sort-union-types",
        "regexp/no-super-linear-move",
        "regexp/prefer-regexp-exec",
        "regexp/prefer-regexp-test",
        "regexp/require-unicode-regexp",
        "regexp/require-unicode-sets-regexp",
        "regexp/sort-character-class-elements",
        "sonarjs/no-exclusive-tests",
        "test-signal/require-assertions",
        "test-signal/require-negative-path",
        "typedoc/require-exported-doc-comment",
        "typedoc/require-exported-doc-comment-description",
        "typedoc/require-throws-tag",
        "tsdoc-require-2/require",
        "typefest/prefer-ts-extras-array-first",
        "typefest/prefer-ts-extras-array-includes",
        "typefest/prefer-ts-extras-array-join",
        "typefest/prefer-ts-extras-array-last",
        "typefest/prefer-ts-extras-assert-defined",
        "typefest/prefer-ts-extras-is-empty",
        "typefest/prefer-ts-extras-key-in",
        "typefest/prefer-ts-extras-object-assign",
        "typefest/prefer-ts-extras-object-keys",
        "typefest/prefer-ts-extras-object-values",
        "typefest/prefer-ts-extras-safe-cast-to",
        "typefest/prefer-ts-extras-string-split",
        "typefest/prefer-type-fest-except",
        "unicorn/consistent-boolean-name",
        "unicorn/consistent-conditional-object-spread",
        "unicorn/consistent-existence-index-check",
        "unicorn/explicit-length-check",
        "unicorn/import-style",
        "unicorn/max-nested-calls",
        "unicorn/no-array-reduce",
        "unicorn/no-array-sort",
        "unicorn/no-array-sort-for-min-max",
        "unicorn/no-computed-property-existence-check",
        "unicorn/no-confusing-array-splice",
        "unicorn/no-duplicate-if-branches",
        "unicorn/no-for-each",
        "unicorn/no-non-function-verb-prefix",
        "unicorn/no-process-exit",
        "unicorn/no-top-level-assignment-in-function",
        "unicorn/no-top-level-side-effects",
        "unicorn/no-manually-wrapped-comments",
        "unicorn/no-unnecessary-splice",
        "unicorn/no-useless-else",
        "unicorn/no-useless-recursion",
        "unicorn/prefer-at",
        "unicorn/prefer-early-return",
        "unicorn/prefer-error-is-error",
        "unicorn/prefer-minimal-ternary",
        "unicorn/prefer-negative-index",
        "unicorn/prefer-number-properties",
        "unicorn/prefer-regexp-test",
        "unicorn/prefer-set-has",
        "unicorn/prefer-short-arrow-method",
        "unicorn/prefer-string-replace-all",
        "unicorn/prefer-ternary",
        "unicorn/require-array-join-separator",
        "unicorn/require-array-sort-compare",
        "vitest/no-conditional-tests",
        "vitest/padding-around-all",
        "vitest/padding-around-test-blocks",
        "vitest/prefer-importing-vitest-globals",
    ].map((ruleName) => [ruleName, "off"])
);

/** @type {import("eslint").Linter.Config[]} */
const config = [
    {
        ignores: [
            ".cache",
            "coverage",
            "dist",
            "node_modules",
        ],
    },
    ...nickTwoBadFourU.configs.all,
    {
        files: [".github/dependabot.yml"],
        name: "Dependabot schema compatibility",
        rules: {
            "json-schema-validator-2/no-invalid": "off",
        },
    },
    {
        files: ["src/**/*.ts"],
        name: "Legacy plugin source compatibility",
        rules: legacySourceRuleOverrides,
    },
];

export default config;
